---
- name: 'Configure and start Confluence'
  become: true
  block:
    - name: 'Create a Confluence systemd service'
      ansible.builtin.template:
        src: 'confluence.service.j2'
        dest: '/etc/systemd/system/confluence.service'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        mode: 0644
      notify: 'Restart Confluence'

    - name: 'Configure the Confluence server settings'
      ansible.builtin.template:
        src: 'server.xml.j2'
        dest: '{{ _confluence_application_path }}/conf/server.xml'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        mode: 0600
      notify: 'Restart Confluence'

    - name: 'Configure the Confluence environment'
      ansible.builtin.template:
        src: 'setenv.sh.j2'
        dest: '{{ _confluence_application_path }}/bin/setenv.sh'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        mode: 0755
      notify: 'Restart Confluence'

    - name: 'Define the Confluence home directory'
      ansible.builtin.template:
        src: 'confluence-init.properties.j2'
        dest: '{{ _confluence_application_path }}/confluence/WEB-INF/classes/confluence-init.properties'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        mode: 0644
      notify: 'Restart Confluence'

    - name: 'Configure the Confluence database connection'
      ansible.builtin.blockinfile:
        path: '{{ _confluence_application_path }}/confluence/WEB-INF/web.xml'
        insertbefore: '</web-app>'
        block: |
          <resource-ref>
            <description>Connection Pool</description>
            <res-ref-name>jdbc/confluence</res-ref-name>
            <res-type>javax.sql.DataSource</res-type>
            <res-auth>Container</res-auth>
          </resource-ref>
      notify: 'Restart Confluence'
      when: confluence_db_configuration | bool

    - name: 'Ensure Confluence is running and enabled at boot'
      ansible.builtin.systemd:
        name: 'confluence'
        state: 'started'
        enabled: true
      when: not ansible_check_mode
