---
- name: 'Configure and start Confluence'
  block:
    - name: 'Create Confluence unit for SystemD'
      ansible.builtin.template:
        src: confluence.service.j2
        dest: /etc/systemd/system/confluence.service
        owner: '{{ confluence_username }}'
        group: '{{ confluence_group }}'
        mode: 0644
      register: _confluence_service

    - name: 'Reload systemd daemon if unit file is changed'
      ansible.builtin.systemd:
        daemon_reload: true
      when: _confluence_service is changed
      notify: Restart Confluence

    - name: 'Configure Confluence'
      ansible.builtin.template:
        src: 'server.xml.j2'
        dest: '{{ _confluence_application_path }}/conf/server.xml'
        owner: '{{ confluence_username }}'
        group: '{{ confluence_group }}'
        mode: 0644
      notify: Restart Confluence

    - name: 'Configure Confluence environment'
      ansible.builtin.template:
        src: 'setenv.sh.j2'
        dest: '{{ _confluence_application_path }}/bin/setenv.sh'
        owner: '{{ confluence_username }}'
        group: '{{ confluence_group }}'
        mode: 0755
      notify: Restart Confluence

    - name: 'Ensure Confluence is running and enabled at boot'
      ansible.builtin.systemd:
        name: confluence
        state: started
        enabled: true
      when: not ansible_check_mode
  become: true
