---

- name: 'Create Confluence unit for SystemD'
  template:
    src: confluence.service.j2
    dest: /etc/systemd/system/confluence.service
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    mode: 0644
  notify: Reload systemctl

- name: 'Start Confluence'
  service:
    name: confluence
    enabled: true
    state: started

- name: 'Configure Confluence'
  template:
    src: 'server.xml.j2'
    dest: '{{ confluence__install_path }}/conf/server.xml'
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    mode: 0644
  notify: Restart Confluence

- name: 'Configure Confluence environment'
  template:
    src: 'setenv.sh.j2'
    dest: '{{ confluence__install_path }}/bin/setenv.sh'
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    mode: 0755
  notify: Restart Confluence
