---

- name: 'Create Confluence unit for SystemD'
  ansible.builtin.template:
    src: confluence.service.j2
    dest: /etc/systemd/system/confluence.service
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    mode: 0644
  notify: Restart Confluence

- name: 'Configure Confluence'
  ansible.builtin.template:
    src: 'server.xml.j2'
    dest: '{{ confluence__application_path }}/conf/server.xml'
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    mode: 0644
  notify: Restart Confluence

- name: 'Configure Confluence environment'
  ansible.builtin.template:
    src: 'setenv.sh.j2'
    dest: '{{ confluence__application_path }}/bin/setenv.sh'
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    mode: 0755
  notify: Restart Confluence
