---
- name: 'Check the current Confluence version'
  ansible.builtin.command:
    cmd: grep -Po '(?<=^version=)\N*$' '{{ _confluence_application_path }}/confluence/META-INF/maven/com.atlassian.confluence/confluence-webapp/pom.properties'
  failed_when: false
  changed_when: false
  register: __confluence_version_check

- name: 'Download and unarchive Confluence'
  when:
    - not ansible_check_mode
    - __confluence_version_check.stdout is not defined or
      confluence_version not in __confluence_version_check.stdout
  block:
    - name: 'Download the Confluence archive to a local folder'
      ansible.builtin.get_url:
        url: '{{ confluence_download_url }}/{{ confluence_archive_name }}'
        dest: '/tmp/{{ confluence_archive_name }}'
        mode: 0644
      delegate_to: localhost

    - name: 'Unarchive Confluence'
      ansible.builtin.unarchive:
        src: '/tmp/{{ confluence_archive_name }}'
        dest: '{{ _confluence_install_path }}'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        extra_opts:
          - '--strip-components=1'
      become: true

- name: 'Create the symbolic link to Confluence installation path'
  ansible.builtin.file:
    src: '{{ _confluence_install_path }}'
    dest: '{{ _confluence_application_path }}'
    state: 'link'
  when: not ansible_check_mode
  become: true
