---

- name: 'Check current Confluence version'
  ansible.builtin.command:
    cmd: grep -Po '(?<=^version=)\N*$' '{{ confluence__application_path }}/confluence/META-INF/maven/com.atlassian.confluence/confluence-webapp/pom.properties'
  failed_when: false
  changed_when: false
  register: confluence__version_check

- name: 'Download and unarchive Confluence'
  ansible.builtin.unarchive:
    src: '{{ confluence__download_url }}'
    dest: '{{ confluence__install_path }}'
    extra_opts:
      - --strip-components=1
    remote_src: true
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
  when:
    - confluence__version_check.stdout is not defined or
      confluence__version not in confluence__version_check.stdout

- name: 'Create symbolic link for Confluence'
  ansible.builtin.file:
    src: '{{ confluence__install_path }}'
    dest: '{{ confluence__application_path }}'
    state: link
