---
- name: 'Include tasks to prepare to install Confluence'
  ansible.builtin.import_tasks: 'pre-install.yml'

- name: 'Include tasks to install Confluence'
  ansible.builtin.import_tasks: 'install.yml'

- name: 'Include tasks to configure Confluence'
  ansible.builtin.import_tasks: 'configure.yml'
