---
- name: 'Prepare for installing Confluence'
  become: true
  block:
    - name: 'Update the APT package cache'
      ansible.builtin.apt:
        update_cache: true
      check_mode: false
      when: ansible_os_family == 'Debian'

    - name: 'Ensure the dependencies are installed'
      ansible.builtin.package:
        name: 'tar'
        state: 'present'

    - name: 'Create a Confluence group'
      ansible.builtin.group:
        name: '{{ confluence_group }}'

    - name: 'Create a Confluence user'
      ansible.builtin.user:
        name: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        comment: 'Atlassian Confluence'
        shell: '/bin/bash'

    - name: 'Create Confluence directories'
      ansible.builtin.file:
        path: '{{ confluence_path }}'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        state: 'directory'
        mode: 0755
      loop:
        - '{{ confluence_install_path }}/{{ confluence_version }}'
        - '{{ confluence_home_path }}'
      loop_control:
        loop_var: confluence_path
