---
- name: 'Create Confluence group'
  ansible.builtin.group:
    name: '{{ confluence__group }}'

- name: 'Create Confluence user'
  ansible.builtin.user:
    name: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    comment: 'Atlassian Confluence'
    shell: /bin/bash
  register: confluence__user_result

- name: 'Create Confluence directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ confluence__username }}'
    group: '{{ confluence__group }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ confluence__install_path }}'
    - '{{ confluence__home_path }}'
