---
- name: 'Prepare to install Confluence'
  become: true
  block:
    - name: 'Create a Confluence group'
      ansible.builtin.group:
        name: '{{ confluence_group }}'

    - name: 'Create a Confluence user'
      ansible.builtin.user:
        name: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        comment: 'Atlassian Confluence'
        shell: '/bin/bash'

    - name: 'Create Confluence directories'
      ansible.builtin.file:
        path: '{{ confluence_path }}'
        owner: '{{ confluence_user }}'
        group: '{{ confluence_group }}'
        state: 'directory'
        mode: 0755
      loop:
        - '{{ _confluence_install_path }}'
        - '{{ confluence_home_path }}'
      loop_control:
        loop_var: confluence_path
