---
- name: Converge
  hosts: all
  vars:
    db_name: 'confluence'
    db_username: 'confluence'
    db_password: 'P@ssw0rd!'

  pre_tasks:
    - name: 'Update apt cache'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.postgresql
      postgresql_users:
        - name: '{{ db_username }}'
          password: '{{ db_password }}'
      postgresql_databases:
        - name: '{{ db_name }}'
          lc_collate: 'en_US.UTF-8'
          lc_ctype: 'en_US.UTF-8'
          encoding: 'UTF-8'
          template: 'template0'
          owner: '{{ db_username }}'
    - role: antmelekhin.confluence
      confluence_db_configuration: true
      confluence_db_address: 127.0.0.1
      confluence_db_port: 5432
      confluence_db_name: '{{ db_name }}'
      confluence_db_username: '{{ db_username }}'
      confluence_db_password: '{{ db_password }}'
