---
# This is an example playbook to execute Ansible tests.

- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:

  - name: 'Gathering Service Facts'
    service_facts:

  - name: 'Assert that confluence service is enabled and running'
    assert:
      that:
        - ansible_facts.services['confluence.service'].state == 'running'
        - ansible_facts.services['confluence.service'].status == 'enabled'

  - name: 'Check url'
    uri:
      url: 'http://{{ ansible_host }}:8090'
