---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that confluence service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['confluence.service'].state == 'running'
          - ansible_facts.services['confluence.service'].status == 'enabled'

    - name: 'Check url'
      ansible.builtin.uri:
        url: 'http://{{ ansible_host }}:8090'

    - name: 'Check current Confluence version'
      ansible.builtin.command:
        cmd: grep -Po '(?<=^version=)\N*$' /opt/atlassian/confluence/confluence/META-INF/maven/com.atlassian.confluence/confluence-webapp/pom.properties
      changed_when: false
      register: confluence__version_check

    - name: 'Version output'
      ansible.builtin.debug:
        var: confluence__version_check.stdout
