---
# This is an example playbook to execute Ansible tests.

- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:

  - name: 'Gathering Service Facts'
    service_facts:

  - name: 'Assert that confluence service is enabled and running'
    assert:
      that:
        - ansible_facts.services['confluence.service'].state == 'running'
        - ansible_facts.services['confluence.service'].status == 'enabled'

  - name: 'Check url'
    uri:
      url: 'http://{{ ansible_host }}:8090'

  - name: 'Check version'
    command: grep ^version /opt/atlassian/confluence/confluence/META-INF/maven/com.atlassian.confluence/confluence-webapp/pom.properties
    register: confluence__version

  - name: 'Debug version'
    debug:
      var: confluence__version.stdout_lines
